sudo: false
language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository
branches:
  only:
    - master
    - dev
    - /^dev\-.*$/
script:
  - ./scripts/build.sh
notifications:
  email: false
