sudo: false
language: android
jdk: oraclejdk8
script: ./gradlew build lint test

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
    email: false
